name: Run batch

on:
  push:
    branches: [ master ]
  schedule:
    - cron: 0 0,12 * * *

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
    - name: Run batch
      run: php batch.php
      env:
        SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
        SLACK_WEBHOOK_ENDPOINT: ${{ secrets.SLACK_WEBHOOK_ENDPOINT }}
        TITLE: ${{ secrets.TITLE }}
